
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 20 15:27:19 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Numero = 19;
  public static final int Auxiliary_Future = 16;
  public static final int Adverb = 3;
  public static final int Verb_Past = 7;
  public static final int Question_Mark = 13;
  public static final int ERROR = 20;
  public static final int Identificador = 18;
  public static final int Verb = 6;
  public static final int Subject = 2;
  public static final int Interrogative_Pronoun = 11;
  public static final int Auxiliary_Future_Negative = 17;
  public static final int Noun = 9;
  public static final int Auxiliary_Past_Negative = 14;
  public static final int EOF = 0;
  public static final int Auxiliary_Past = 15;
  public static final int Time_Expression = 5;
  public static final int Adjective = 4;
  public static final int error = 1;
  public static final int Conector = 10;
  public static final int Article = 8;
  public static final int Possessive_Pronoun = 12;
}

